package com.amazon.ebook.booklet.msp;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.KeyEvent;

import com.amazon.ebook.framework.gui.foundation.SymbolPopup;
import com.amazon.ebook.framework.gui.foundation.x;

// key events which has SymbolPopup as source are treated specially 
// in dxg's web browser.
// Extends x so that we can construct a SymbolePopup 
// 
//com.amazon.ebook.booklet.msp.Controller
public class g extends x {
	private static final long serialVersionUID = 1L;
	private DBusEventHandler myDBusEventHandler = null;

	public g() {
		super();
		if (myDBusEventHandler == null) {
			try {
				myDBusEventHandler = new DBusEventHandler(new SymbolPopup(this));
			} catch (Exception ex) {
				System.out.println("error");
				ex.printStackTrace();
			}
		}
	}

	// following codes are generated by eclipse
	protected void c(Graphics arg0) {
		// TODO Auto-generated method stub
	}

	public void u() {
		// TODO Auto-generated method stub

	}

	protected void A(Graphics arg0) {
		// TODO Auto-generated method stub

	}

	public Dimension a(Graphics arg0) {
		// TODO Auto-generated method stub
		return null;
	}

	public void keyPressed(KeyEvent arg0) {
		// TODO Auto-generated method stub

	}

	public void keyReleased(KeyEvent arg0) {
		// TODO Auto-generated method stub

	}

	public void keyTyped(KeyEvent arg0) {
		// TODO Auto-generated method stub

	}

	public String H() {
		// TODO Auto-generated method stub
		return null;
	}

}
